hack/urls.py
from django.urls import path

from .import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.index, name="index"),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path("logout", views.logout, name="logout"),
    path("problems", views.form, name="problems"),
    path("contactus", views.contactus, name="contactus"),
    path("team_register", views.team_register, name="team_register"),
    path("profile", views.profile, name="profile"),
    path('editprofile/<int:reg_pk>/', views.editprofile , name = "editprofile"),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name="reset_password"),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),name="password_reset_complete"),
    #path("team_detail", views.team_detail, name="team_detail"),

    ]

hackathonsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('hack.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hack/models.py
from django.db import models
from django.contrib.auth.models import User
Gender_CHOICES = (
    ('Male','Male'),
    ('Female', 'Female'),
    ('Other','Other'),
)
# Create your models here.

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    #team_name = models.ForeignKey(Reg , null = True, on_delete=models.SET_NULL)
    return 'user_name_{0}/{1}'.format(instance.user.username , filename)

class problem(models.Model):

    problem_id = models.TextField(default="")
    title = models.TextField()
    desc = models.TextField()
    #problem_upload = models.FileField( blank=True ,default="", upload_to=user_directory_path)

    def __str__(self):
        return self.problem_id

class Reg(models.Model):

    user = models.ForeignKey(User , on_delete = models.CASCADE)

    Team_name = models.CharField(max_length = 50)
    M1_Name = models.CharField(max_length = 100 )
    M1_email = models.EmailField(null = True)
    M1_Mobile_no = models.CharField(null = True, max_length = 10)
    M1_gender = models.CharField(max_length=10, choices=Gender_CHOICES ,null=True)

    M2_Name = models.CharField(max_length = 100 )
    M2_email = models.EmailField(null = True)
    M2_Mobile_no = models.CharField(null = True, max_length = 10)
    M2_gender = models.CharField(max_length=10, choices=Gender_CHOICES ,null=True)

    M3_Name = models.CharField(max_length = 100)
    M3_email = models.EmailField(null = True)
    M3_Mobile_no = models.CharField(null = True, max_length = 10)
    M3_gender = models.CharField(max_length=10, choices=Gender_CHOICES ,null=True)

    M4_Name = models.CharField(max_length = 100 , blank=True)
    M4_email = models.EmailField(blank=True )
    M4_Mobile_no = models.CharField(max_length = 10 , blank=True )
    M4_gender = models.CharField(max_length=10, choices=Gender_CHOICES  , blank=True )

    M5_Name = models.CharField(max_length = 100 , blank=True )
    M5_email = models.EmailField( blank=True )
    M5_Mobile_no = models.CharField( max_length = 10, blank=True )
    M5_gender = models.CharField(max_length=10, choices=Gender_CHOICES , blank=True )

    Mentor_Name = models.CharField(max_length = 100 ,default =" ")
    Mentor_email = models.EmailField(null = True ,default =" ")
    Mentor_Mobile_no = models.CharField(null = True, max_length = 10 , default =" ")
    Mentor_gender = models.CharField(max_length=10, choices=Gender_CHOICES ,null=True,default =" ")

    def __str__(self):
        return self.Team_name



class ideas(models.Model):

    user = models.ForeignKey(User ,default="", on_delete = models.CASCADE)
    problem_id = models.ForeignKey(problem ,default="" , null = True, on_delete=models.SET_NULL)
    idea = models.FileField( blank=True ,default="", upload_to=user_directory_path)

    def __str__(self):
        return str(self.user)


class contactus(models.Model):

    name = models.CharField( max_length=200)
    user = models.ForeignKey(User ,default="", on_delete = models.CASCADE)
    email = models.EmailField()
    subject = models.TextField()

    def __str__(self):
        return str(self.user)

hackathonsite/templates/base.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="login" method="Post">
        {% csrf_token %}
        <p>
            Username :
            <input type="text" name="username" id="">
        </p>
        <p>
            Password :
            <input type="password" name="password" id="password">
        </p>
        <a href="{% url 'reset_password' %}">Forgot Password??</a><br><br>
        <input type="submit" value="Submit">
    </form>
    <div>
        {% for message in messages %}
            <h3>
                {{message}}
            </h3>
        {% endfor %}
    </div>
</body>
</html> -->

{% load static %}
{% static "images" as baseUrl %}
<!DOCTYPE html>
<html lang="en">

<head>
	
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Travello template project">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
	<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'styles/contactus.css' %}">
    <!-- <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
    </style> -->
</head>

<body>
    
	<div class="super_container" style="background: linear-gradient(135deg, #71b7e6, #9b59b6);">

		<!-- Header -->

		<header class="header">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="header_content d-flex flex-row align-items-center justify-content-start">
							<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
								<div class="logo"><a href="{% url 'index' %}">Vishwa-Hackathon</a></div>
								<nav class="main_nav">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li class="active"><a href="{% url 'index' %}">Home</a></li>
										

										{% if user.is_authenticated %}
											<li><a href="contactus">Contact</a></li>
											<li><a href="profile">Hello, {{user.first_name}}</a></a></li>
											{% if forms|length == 0 %}
												<li><a href="team_register">Team Register</a></li>
											{% endif %}
											<li><a href="problems">Problem Statements</a></li>
											<li><a href="logout">Logout</a></li>
										{% else %}
											<li><a href="register">Register</a></li>
											<li><a href="login">Login</a></li>
										{% endif %}
									</ul>
								</nav>
								<!-- <div class="header_phone ml-auto">Call us: 00-56 445 678 33</div> -->

								<!-- Hamburger -->

								<div class="hamburger ml-auto">
									<i class="fa fa-bars" aria-hidden="true"></i>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- <div class="header_social d-flex flex-row align-items-center justify-content-start">
				<ul class="d-flex flex-row align-items-start justify-content-start">
					<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-discord" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
				</ul>
			</div> -->
		</header>

		<!-- Menu -->

		<div class="menu">
			<div class="menu_header d-flex flex-row align-items-center justify-content-start">
				<div class="menu_logo"><a href="index.html">Vishwa-Hackathon</a></div>
				<div class="menu_close_container ml-auto">
					<div class="menu_close">
						<div></div>
						<div></div>
					</div>
				</div>
			</div>
			<div class="menu_content">
				<ul>
					<li><a href="index.html">Home</a></li>
					{% if user.is_authenticated %}
					<li><a href="profile">Hello, {{user.first_name}}</a></a></li>
					{% if forms|length == 0 %}
						<li><a href="team_register">Team Register</a></li>
					{% endif %}
						<li><a href="problems">Problem Statements</a></li>
						<li><a href="logout">Logout</a></li>
					{% else %}
							<li><a href="register">Register</a></li>
							<li><a href="login">Login</a></li>
					{% endif %}
					<li><a href="contactus">Contact</a></li>

				</ul>
			</div>
			<!-- <div class="menu_social">
				<div class="menu_phone ml-auto">Call us: 00-56 445 678 33</div>
				<ul class="d-flex flex-row align-items-start justify-content-start">
					<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
					<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
				</ul>
			</div> -->
		</div>

		 <!-- Home -->

		<!-- <div class="home"> -->
            {% block content %}
            {% endblock %}
        <!-- </div> -->
    </div>

						<script src="{% static 'js/jquery-3.2.1.min.js' %}">
						</script>
						<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
						<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
						<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
						<script src="{% static 'plugins/Isotope/isotope.pkgd.min.js' %}"></script>
						<script src="{% static 'plugins/scrollTo/jquery.scrollTo.min.js' %}"></script>
						<script src="{% static 'plugins/easing/easing.js' %}"></script>
						<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
						<script src="{% static 'js/custom.js' %}"></script>

                        
                    </body>

</html>

hackathonsite/templates/contactus.html
{% load static %}

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'styles/contactus.css' %}">
</head>
<body>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
      <label for="name">Name</label>
      <input type="text" name="name" maxlength="50" required id="id_name">
  
      <label>Email Id</label>
      <br>
      <input type="email" name="email" maxlength="254" required id="id_email">
      <br><br>
      <label for="subject">Subject</label>
      <textarea name="subject" cols="40" rows="10" required id="id_subject"></textarea>
  
      <input type="submit" value="Submit" onclick="contactus()">
    </form>
</body>

hackathonsite/templates/edit.html
{% load static %}
{% if error %}
    <div class="alert alert-danger text-danger" role="alert">
        {{ error }}
    </div>
{% endif %}
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" ></script>
  <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body style="background-color: #eee;">




  <div class="container" style="background-color: white;border-radius: 8px;border: 2px solid #333;">
    <!-- added new div here -->
    <h2 class="heading" style="padding: 1%;"><strong>Hackathon Registration</strong> Form <span></span></h2>
    <hr>
    <form enctype="multipart/form-data" method="post">
  {% csrf_token %}

  <div class="form-row">
    <legend>Team Details </legend>
      <div class="form-group col-md-4">
          <label for="id_Team_name">Team name:</label> <input type="text" name="Team_name" value="{{ f1.Team_name }}" maxlength="50" required id="id_Team_name">
      </div>

  </div>
</div>


<br>


<div class="container" style="background-color: white;border-radius: 7px;border: 2px solid #333;">
  <div class="form-row">
    <legend>Member1's Details</legend>
      <br>
      <div class="form-group col-md-4">
      <label for="id_M1_Name">Name:</label> <input type="text" name="M1_Name" value="{{ f1.M1_Name }}" maxlength="100" required id="id_M1_Name">
      </div>
      <div class="form-group col-md-4">
        <label for="id_M1_email">email:</label> <input type="email" name="M1_email" value="{{ f1.M1_email }}" maxlength="254" required id="id_M1_email">
      </div>
      <div class="form-group col-md-4">
        <label for="id_M1_Mobile_no">Mobile no:</label> <input type="text" name="M1_Mobile_no" value="{{ f1.M1_Mobile_no }}" maxlength="10" required id="id_M1_Mobile_no">
      </div>
      <div class="form-group col-md-4">
        <label for="id_M1_gender">Gender:</label> <select name="M1_gender" required id="id_M1_gender">
          <option value="{{ f1.M1_gender }}" selected>{{ f1.M1_gender }}</option>
          <option value="Male">Male</option>
          <option value="Female">Female</option>
          <option value="Other">Other</option>
        </select>
      </div>
  </div>
</div>
<br>

<div class="container" style="background-color: white;border-radius: 7px;border: 2px solid #333;">
  <div class="form-row">
      <br>
      <legend>Member2's Details</legend>
      <div class="form-group col-md-4">
        <label for="id_M2_Name">Name:</label> <input type="text" name="M2_Name" value="{{ f1.M2_Name }}" maxlength="100" required id="id_M2_Name">
      </div>
      <div class="form-group col-md-4">
        <label for="id_M2_email">Email:</label> <input type="email" name="M2_email" value="{{ f1.M2_email }}" maxlength="254" required id="id_M2_email">
      </div>
      <div class="form-group col-md-4">
        <label for="id_M2_Mobile_no">Mobile no:</label> <input type="text" name="M2_Mobile_no" value="{{ f1.M2_Mobile_no }}" maxlength="10" required id="id_M2_Mobile_no">
      </div>
      <div class="form-group col-md-4">
        <label for="id_M2_gender">Gender:</label> <select name="M2_gender" required id="id_M2_gender">
          <option value="{{ f1.M2_gender }}" selected>{{ f1.M2_gender }}</option>
          <option value="Male" >Male</option>
          <option value="Female">Female</option>
          <option value="Other">Other</option>
        </select>
      </div>
  </div>
  </div>
  <br>

  <div class="container" style="background-color: white;border-radius: 7px;border: 2px solid #333;">
    <div class="form-row">
        <br>
        <legend>Member3's Details</legend>
        <div class="form-group col-md-4">
        <label for="id_M3_Name">Name:</label> <input type="text" name="M3_Name" value="{{ f1.M3_Name }}" maxlength="100" required id="id_M3_Name">
        </div>
        <div class="form-group col-md-4">
          <label for="id_M3_email">Email:</label> <input type="email" name="M3_email" value="{{ f1.M3_email }}" maxlength="254" required id="id_M3_email">
        </div>
        <div class="form-group col-md-4">
          <label for="id_M3_Mobile_no">Mobile no:</label> <input type="text" name="M3_Mobile_no" value="{{ f1.M3_Mobile_no }}" maxlength="10" required id="id_M3_Mobile_no">
        </div>
        <div class="form-group col-md-4">
          <label for="id_M3_gender">Gender:</label> <select name="M3_gender" required id="id_M3_gender">
            <option value="{{ f1.M3_gender }}" selected>{{ f1.M3_gender }}</option>
            <option value="Male" >Male</option>
            <option value="Female">Female</option>
          <option value="Other">Other</option>
          </select>
        </div>
    </div>
    </div>
    <br>

    <div class="container" style="background-color: white;border-radius: 7px;border: 2px solid #333;">
      <div class="form-row">
          <br>
          <legend>Member4's Details</legend>
          <div class="form-group col-md-4">
            <label for="id_M4_Name">Name:</label> <input type="text" name="M4_Name" value="{{ f1.M4_Name }}" maxlength="100" id="id_M4_Name">
          </div>
          <div class="form-group col-md-4">
            <label for="id_M4_email">Email:</label> <input type="email" name="M4_email" value="{{ f1.M4_email }}" maxlength="254" id="id_M4_email">
          </div>
          <div class="form-group col-md-4">
            <label for="id_M4_Mobile_no">Mobile no:</label> <input type="text" name="M4_Mobile_no" value="{{ f1.M4_Mobile_no }}" maxlength="10" id="id_M4_Mobile_no">
          </div>
          <div class="form-group col-md-4">
            <label for="id_M4_gender" >Gender:</label> <select name="M4_gender" id="id_M4_gender">
              <option value="{{ f1.M4_gender }}" selected>{{ f1.M4_gender }}</option>
              <option value="Male" >Male</option>
              <option value="Female">Female</option>
              <option value="Other">Other</option>
            </select>
          </div>
      </div>
      </div>
      <br>

      <div class="container" style="background-color: white;border-radius: 7px;border: 2px solid #333;">
        <div class="form-row">
            <br>
            <legend>Member5's Details</legend>
            <div class="form-group col-md-4">
            <label for="id_M5_Name">Name:</label> <input type="text" name="M5_Name" value="{{ f1.M5_Name }}" maxlength="100" id="id_M5_Name">
            </div>
            <div class="form-group col-md-4">
              <label for="id_M5_email">Email:</label> <input type="email" name="M5_email" value="{{ f1.M5_email }}" maxlength="254" id="id_M5_email">
            </div>
            <div class="form-group col-md-4">
            <label for="id_M5_Mobile_no">Mobile no:</label> <input type="text" value="{{ f1.M5_Mobile_no }}" name="M5_Mobile_no" maxlength="10" id="id_M5_Mobile_no">
            </div>
            <div class="form-group col-md-4">
              <label for="id_M5_gender">Gender:</label> <select name="M5_gender" id="id_M5_gender">
                <option value="{{ f1.M5_gender }}" selected>{{ f1.M5_gender }}</option>
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
              </select>
            </div>
        </div>
        </div>
        <br>

        <br>
        <div class="container" style="background-color: white;border-radius: 7px;border: 2px solid #333;">
          <div class="form-row">
              <br>
              <legend>Mentor's Details</legend>
              <div class="form-group col-md-4">
                <label for="id_Mentor_Name">Name:</label> <input type="text" name="Mentor_Name" value="{{ f1.Mentor_Name }}" maxlength="100" required id="id_Mentor_Name">
              </div>
              <div class="form-group col-md-4">
                <label for="id_Mentor_email">Email:</label> <input type="email" name="Mentor_email" value="{{ f1.Mentor_email }}" maxlength="254" required id="id_Mentor_email">
              </div>
              <div class="form-group col-md-4">
                <label for="id_Mentor_Mobile_no">Mobile no:</label> <input type="text" name="Mentor_Mobile_no" value="{{ f1.Mentor_Mobile_no }}" maxlength="10" required id="id_Mentor_Mobile_no">
              </div>
              <div class="form-group col-md-4">
                <label for="id_Mentor_gender">Gender:</label> <select name="Mentor_gender" id="id_Mentor_gender">
                  <option value="{{ f1.Mentor_gender }}" selected>{{ f1.Mentor_gender }}</option>
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                  <option value="Other">Other</option>
                </select>
              </div>
          </div>
          </div>
          <br>
          <div class="container">
            <button type="submit" class="btn btn-success btn-lg btn-block" style="width: 20%;">Save</button>
          </div>

          <br>






              <!-- reduced size of submit button -->
              <br>
            </div>
            <br>


</form>

<br>
</body>

hackathonsite/templates/home1.html
{%extends 'base.html'%}

{% block content %}

<h1>Hello {{name}}!!!</h1>

<form action="add" method="post">

{% csrf_token %}
Enter 1 no. : <input type="text" name="num1"><br>
Enter 2 no. : <input type="text" name="num2"><br>
<input type="submit" >
</form>
{% endblock %}

hackathonsite/templates/password_reset.html
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link rel="stylesheet" href="{% static 'main/forgot.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
 <div class="form-gap"></div>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="text-center">
                  <h3><i class="fa fa-lock fa-4x"></i></h3>
                  <h2 class="text-center">Forgot Password?</h2>
                  <p>You can reset your password here.</p>
                  <div class="panel-body">

                    <form id="register-form" role="form" autocomplete="off" class="form" method="POST">
                        {% csrf_token %}
                      <div class="form-group">
                        <div class="input-group">
                          <span class="input-group-addon"><i class="glyphicon glyphicon-envelope color-blue"></i></span>
                          <input required id="id_email" autocomplete="email" name="email" maxlength="254" placeholder="email address" class="form-control"  type="email">
                        </div>
                      </div>
                      <div class="form-group">
                        <input name="recover-submit" class="btn btn-lg btn-primary btn-block" value="Reset Password" type="submit">
                      </div>
                      <input type="hidden" class="hide" name="token" id="token" value="">
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
	</div>
</div>

hackathonsite/templates/password_reset_done.html
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">

<div class="alert alert-success" role="alert">
<h3>Password reset complete</h3>
</div>
<p>Your password has been set. You may go ahead and log in now.</p>

<a href="{% url 'login' %}">Log in</a>

hackathonsite/templates/password_reset_sent.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
<div class="alert alert-success" role="alert">
<h3>Password reset sent</h3>
</div>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
<a href="{% url 'login' %}">Log in</a>

hackathonsite/templates/result.html
{%extends 'base.html'%}

{% block content %}

Result : {{Result}}
{% endblock %}